// This file generated by create-i18n-locale-resources script

import { Language, Translation } from './types';

import { resourcesEN } from './resources/en';
import { resourcesRU } from './resources/ru';

export const resources: Translation = {
  [Language.EN]: resourcesEN,
  [Language.RU]: resourcesRU,
};
