// This file generated by create-locale-resources script

import { Language, Translation } from './types.ts';
import { resourcesEN } from './resources/en';
import { resourcesRU } from './resources/ru';

export const resources: Translation = {
  [Language.EN]: resourcesEN,
  [Language.RU]: resourcesRU,
}
