// This file generated by create-i18n-locale-resources script
import roleEN from '../locales/en/abac/role.json';
import dateEN from '../locales/en/common/date.json';
import filterEN from '../locales/en/components/filter.json';
import infoCardEN from '../locales/en/components/info-card.json';
import selectEN from '../locales/en/components/select.json';
import sharedFilterEN from '../locales/en/components/shared-filter.json';
import tableEN from '../locales/en/components/table.json';
import workInProgressEN from '../locales/en/components/work-in-progress.json';
import warningEN from '../locales/en/components/modals/warning.json';
import metricPrefixEN from '../locales/en/helpers/metric-prefix.json';
import errorPageEN from '../locales/en/pages/error-page.json';
import invitePageEN from '../locales/en/pages/invite-page.json';
import loginPageEN from '../locales/en/pages/login-page.json';
import notFoundPageEN from '../locales/en/pages/not-found-page.json';
import resetPasswordPagesEN from '../locales/en/pages/reset-password-pages.json';

export const resourcesEN = {
	'role': roleEN,
	'date': dateEN,
	'filter': filterEN,
	'info-card': infoCardEN,
	'select': selectEN,
	'shared-filter': sharedFilterEN,
	'table': tableEN,
	'work-in-progress': workInProgressEN,
	'warning': warningEN,
	'metric-prefix': metricPrefixEN,
	'error-page': errorPageEN,
	'invite-page': invitePageEN,
	'login-page': loginPageEN,
	'not-found-page': notFoundPageEN,
	'reset-password-pages': resetPasswordPagesEN,
}
