// This file generated by create-i18n-locale-resources script
import roleRU from '../locales/ru/abac/role.json';
import dateRU from '../locales/ru/common/date.json';
import filterRU from '../locales/ru/components/filter.json';
import infoCardRU from '../locales/ru/components/info-card.json';
import selectRU from '../locales/ru/components/select.json';
import sharedFilterRU from '../locales/ru/components/shared-filter.json';
import tableRU from '../locales/ru/components/table.json';
import workInProgressRU from '../locales/ru/components/work-in-progress.json';
import warningRU from '../locales/ru/components/modals/warning.json';
import metricPrefixRU from '../locales/ru/helpers/metric-prefix.json';
import errorPageRU from '../locales/ru/pages/error-page.json';
import invitePageRU from '../locales/ru/pages/invite-page.json';
import loginPageRU from '../locales/ru/pages/login-page.json';
import notFoundPageRU from '../locales/ru/pages/not-found-page.json';
import resetPasswordPagesRU from '../locales/ru/pages/reset-password-pages.json';

export const resourcesRU = {
	'role': roleRU,
	'date': dateRU,
	'filter': filterRU,
	'info-card': infoCardRU,
	'select': selectRU,
	'shared-filter': sharedFilterRU,
	'table': tableRU,
	'work-in-progress': workInProgressRU,
	'warning': warningRU,
	'metric-prefix': metricPrefixRU,
	'error-page': errorPageRU,
	'invite-page': invitePageRU,
	'login-page': loginPageRU,
	'not-found-page': notFoundPageRU,
	'reset-password-pages': resetPasswordPagesRU,
}
